---
title: "Question 4: Portfolio Commentary"
author: "Liam Andrew Beattie - 22562435"
date: "`r Sys.Date()`"
output: powerpoint_presentation
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, fig.width=8, fig.height=6, fig.align='center', fig.pos="H", fig.pos = 'H')
rm(list = ls()) # Clean your environment:
gc() 
source("code/install_and_load.R")
install_and_load(c("tidyverse","zoo","ggplot2","xts","treemap","PerformanceAnalytics"))

list.files('code/', full.names = T, recursive = T) %>% .[grepl('.R', .)] %>% as.list() %>% walk(~source(.))

Port_Holds <- read_rds("data/Fund_Holds.rds")
Port_Rets <- read_rds("data/Fund_Rets.rds")
BM_Holds <- read_rds("data/BM_Holds.rds")
BM_Rets <- read_rds("data/BM_Rets.rds")
    

```


```{r data-wrangling, include=FALSE}
# Pipeline to merge, process, and calculate rolling metrics
tidy_data <- merge_and_prepare_returns_data(Port_Rets, BM_Rets) %>%
  convert_returns_data_to_xts() %>%
  {
    # Step inside the pipe to calculate active returns and rolling metrics
    active_returns <- compute_active_returns(.)
    rolling_te <- calculate_rolling_tracking_error(active_returns, width = 12)
    rolling_dd <- calculate_rolling_downside_deviation(., width = 12)
    
    # Combine rolling metrics into tidy data
    create_tidy_data_for_plotting(rolling_te, rolling_dd)
  }

```


---

## Relative Risk

```{r plot-TE-and_DE}

tidy_data %>% plot_tidy_data_over_time(title = "Tracking Error and Downside Risk Over Time")
```

---

## Relative Performance 

```{r cum-returns-Port-and-BM}
merge_and_prepare_returns_data(Port_Rets, BM_Rets) %>%  
chart.CumReturns(
  
  wealth.index = TRUE,  # Display returns as a wealth index
  legend.loc = "topleft",  # Place legend on the top left
  main = "Cumulative Returns: Fund vs. Benchmark",
  colorset = c("blue", "red")
)

```


---

## Fund Positioning

```{r sector-treemap-current}
create_treemap(Port_Holds, BM_Holds, N = 0)
```


---

Resources holdings spike at the begining of 2020

```{r sector-composition-over-time}
create_sector_area_graph(Port_Holds, BM_Holds)
```

---


We see that at the beginning of 2020 the Portfolio was dominated by Glencore PLC 

```{r sector-treemap-ats-pike}
create_treemap(Port_Holds, BM_Holds, N = 0,date=as.Date("31/01/2020", format = "%d/%m/%Y"))
```





